=== ekarjun/Arjun_RA/arjun_ra/model/schema/models/Alarm.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "Alarm",
    "properties": {
        "id": { "type": "string" },
        "meName": { "type": "string" },
        "metype": { "type": "string" },
        "probCause": { "type": "string" },
        "probCauseQual": { "type": "string" },
        "nelastSettime": { "type": "string" },
        "nelastcleartime": { "type": "string" },
        "nereportedtime": { "type": "string" },
        "serviceaffecting": { "enum": ["Unknown", "ServiceAffecting", "NonServiceAffecting"] },
        "addtext": { "type": "string" },
        "severity": { "enum": ["Indeterminate", "NonAlarmed", "Free_Choice", "Warning",
            "Minor", "Major", "Critical", "Cleared"] }
    },
    "additionalProperties": false,
    "required": ["id", "meName", "metype", "probCause", "probCauseQual", "nelastSettime", "nelastcleartime", 
        "nereportedtime", "serviceaffecting", "addtext", "severity"]
}

=== ekarjun/Arjun_RA/arjun_ra/model/data/example-active-alarms.json
[
  {
    "id": "23",
    "meName": "Power Supply Bay 0",
    "metype": "50000",
    "probCause": "NA",
    "probCauseQual": "NA",
    "nelastSettime": "07072014 154300",
    "nelastcleartime": "",
    "nereportedtime": "07072014 154300",
    "serviceaffecting": "Unknown",
    "addtext": "Power Supply/FAN Module Missing [0]",
    "severity": "Critical"
    }, 
  {
    "id": "45",
    "meName": "GigabitEthernet0/0/3",
    "metype": "50000",
    "probCause": "NA",
    "probCauseQual": "NA",
    "nelastSettime": "07072014 154350",
    "nelastcleartime": "",
    "nereportedtime": "07072014 154350",
    "serviceaffecting": "ServiceAffecting",
    "addtext": "Physical Port Link Down [1]",
    "severity": "Critical"
    },
 {
    "id": "56",
    "meName": "GigabitEthernet0/0/4",
    "metype": "50000",
    "probCause": "NA",
    "probCauseQual": "NA",
    "nelastSettime": "07072014 154352",
    "nelastcleartime": "",
    "nereportedtime": "07072014 154352",
    "serviceaffecting": "ServiceAffecting",
    "addtext": "Physical Port Link Down [1]",
    "severity": "Critical"
  }
]
