=== ekarjun/Arjun_RA/arjun_ra/model/schema/models/EquipmentHolder.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "show-equipment-holders in-schema",
    "type": "object",
    "properties": {
        "userLabel": { "type": "string" },
        "acceptableEquipmentTypeList": { "type": "array", "items": [{"type": "string"}] },
        "name": { "type": "string" },
        "id": { "type": "string" },
        "alarmStatus": { "$ref": "AlarmStatus.json" },
        "holderState": { "enum": ["MISMATCH_OF_INSTALLED_AND_EXPECTED", "UNAVAILABLE", "UNKNOWN", "EXPECTED_AND_NOT_INSTALLED", "INSTALLED_AND_NOT_EXPECTED", "INSTALLED_AND_EXPECTED", "EMPTY"] },
        "alarmReportingIndicator": { "type": "boolean" },
        "owner": { "type": "string" },
        "holderType": { "enum": ["slot", "sub_slot", "shelf", "sub_shelf", "rack"] },
        "containingEquipment": { "$ref": "NullableRef.json" },
        "expectedOrInstalledEquipment": { "$ref": "NullableRef.json" },
        "nativeEMSName": { "type": "string" }
    },
    "additionalProperties": false,
    "required": [
        "userLabel", "acceptableEquipmentTypeList", "name", "id", "alarmStatus", 
        "holderState", "alarmReportingIndicator", "owner", "holderType",
        "containingEquipment", "expectedOrInstalledEquipment", "nativeEMSName"]
}

=== ekarjun/Arjun_RA/arjun_ra/model/data/example-equipment-holders.json
[
  {
    "userLabel": "",
    "acceptableEquipmentTypeList": [],
    "name": "0",
    "id": "0",
    "alarmStatus": "Indeterminate",
    "holderState": "INSTALLED_AND_EXPECTED",
    "alarmReportingIndicator": false,
    "owner": "",
    "holderType": "shelf",
    "containingEquipment": null,
    "expectedOrInstalledEquipment": "0",
    "nativeEMSName": ""
  },
  {
    "userLabel": "",
    "acceptableEquipmentTypeList": [],
    "name": "0-1",
    "id": "0-1",
    "alarmStatus": "Indeterminate",
    "holderState": "INSTALLED_AND_EXPECTED",
    "alarmReportingIndicator": false,
    "owner": "",
    "holderType": "slot",
    "containingEquipment": "0",
    "expectedOrInstalledEquipment": "0-1",
    "nativeEMSName": ""
  },
  {
    "userLabel": "",
    "acceptableEquipmentTypeList": [],
    "name": "0-2",
    "id": "0-2",
    "alarmStatus": "Indeterminate",
    "holderState": "INSTALLED_AND_EXPECTED",
    "alarmReportingIndicator": false,
    "owner": "",
    "holderType": "slot",
    "containingEquipment": "0",
    "expectedOrInstalledEquipment": "0-2",
    "nativeEMSName": ""
  },
  {
    "userLabel": "",
    "acceptableEquipmentTypeList": [],
    "name": "0-3",
    "id": "0-3",
    "alarmStatus": "Indeterminate",
    "holderState": "INSTALLED_AND_EXPECTED",
    "alarmReportingIndicator": false,
    "owner": "",
    "holderType": "slot",
    "containingEquipment": "0",
    "expectedOrInstalledEquipment": "0-3",
    "nativeEMSName": ""
  },
  {
    "userLabel": "",
    "acceptableEquipmentTypeList": [],
    "name": "0-4",
    "id": "0-4",
    "alarmStatus": "Indeterminate",
    "holderState": "INSTALLED_AND_EXPECTED",
    "alarmReportingIndicator": false,
    "owner": "",
    "holderType": "slot",
    "containingEquipment": "0",
    "expectedOrInstalledEquipment": "0-4",
    "nativeEMSName": ""
  }
]
