=== ekarjun/Arjun_RA/arjun_ra/model/schema/models/Equipment.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "Equipment",
    "type": "object",
    "properties": {
        "userLabel": { "type": "string" },
        "containingEquipmentHolder": { "$ref": "Ref.json" },
        "name": { "type": "string" },
        "id": { "type": "string" },
        "alarmStatus": { "$ref": "AlarmStatus.json" },
        "installedEquipmentObjectType": { "type": "string" },
        "installedVersion": { "type": "string" },
        "supportedTps": { "type": "array", "items": [{"$ref": "Ref.json"}] },
        "alarmReportingIndicator": { "type": "boolean" },
        "serviceState": { "enum": ["OUT_OF_SERVICE_BY_MAINTENANCE", "SERV_NA", "OUT_OF_SERVICE", "IN_SERVICE"] },
        "owner": { "type": "string" },
        "installedSerialNumber": { "type": "string" },
        "installedPartNumber": { "type": "string" },
        "expectedEquipmentObjectType": { "type": "string" },
        "containedEquipmentHolders": { "type": "array", "items": [{"$ref": "Ref.json"}] },
        "nativeEMSName": { "type": "string" }
    },
    "additionalProperties": false,
    "required": [
        "userLabel", "containingEquipmentHolder", "name", "id", "alarmStatus", 
        "installedEquipmentObjectType", "installedVersion", "supportedTps", "alarmReportingIndicator",
        "serviceState", "owner", "installedSerialNumber", "installedPartNumber", "expectedEquipmentObjectType",
        "containedEquipmentHolders", "nativeEMSName"]
}

=== ekarjun/Arjun_RA/arjun_ra/model/data/example-equipment.json
[
  {
    "userLabel": "",
    "containingEquipmentHolder": "0",
    "name": "0",
    "id": "0",
    "alarmStatus": "Indeterminate",
    "installedEquipmentObjectType": "ASR-903",
    "installedVersion": "",
    "supportedTps": [],
    "alarmReportingIndicator": false,
    "serviceState": "IN_SERVICE",
    "owner": "",
    "installedSerialNumber": "FOX1546P0P1",
    "installedPartNumber": "ASR-903",
    "expectedEquipmentObjectType": "ASR-903",
    "containedEquipmentHolders": [
      "0-1",
      "0-2",
      "0-3",
      "0-4"
    ],
    "nativeEMSName": ""
  },
  {
    "userLabel": "",
    "containingEquipmentHolder": "0-1",
    "name": "0-1",
    "id": "0-1",
    "alarmStatus": "Indeterminate",
    "installedEquipmentObjectType": "A900-IMA4OS",
    "installedVersion": "",
    "supportedTps": [],
    "alarmReportingIndicator": false,
    "serviceState": "IN_SERVICE",
    "owner": "",
    "installedSerialNumber": "FOC1612862W",
    "installedPartNumber": "A900-IMA4OS",
    "expectedEquipmentObjectType": "A900-IMA4OS",
    "containedEquipmentHolders": [],
    "nativeEMSName": ""
  },
  {
    "userLabel": "",
    "containingEquipmentHolder": "0-2",
    "name": "0-2",
    "id": "0-2",
    "alarmStatus": "Indeterminate",
    "installedEquipmentObjectType": "A900-IMA8T",
    "installedVersion": "",
    "supportedTps": [
      "GigabitEthernet-0-2-0",
      "GigabitEthernet-0-2-1",
      "GigabitEthernet-0-2-2",
      "GigabitEthernet-0-2-3",
      "GigabitEthernet-0-2-4",
      "GigabitEthernet-0-2-5",
      "GigabitEthernet-0-2-6",
      "GigabitEthernet-0-2-7"
    ],
    "alarmReportingIndicator": false,
    "serviceState": "IN_SERVICE",
    "owner": "",
    "installedSerialNumber": "FOC154381PA",
    "installedPartNumber": "A900-IMA8T",
    "expectedEquipmentObjectType": "A900-IMA8T",
    "containedEquipmentHolders": [],
    "nativeEMSName": ""
  },
  {
    "userLabel": "",
    "containingEquipmentHolder": "0-3",
    "name": "0-3",
    "id": "0-3",
    "alarmStatus": "Indeterminate",
    "installedEquipmentObjectType": "A900-IMA1X",
    "installedVersion": "",
    "supportedTps": [
      "TenGigabitEthernet-0-3-0"
    ],
    "alarmReportingIndicator": false,
    "serviceState": "IN_SERVICE",
    "owner": "",
    "installedSerialNumber": "FOC160880FX",
    "installedPartNumber": "A900-IMA1X",
    "expectedEquipmentObjectType": "A900-IMA1X",
    "containedEquipmentHolders": [],
    "nativeEMSName": ""
  },
  {
    "userLabel": "",
    "containingEquipmentHolder": "0-4",
    "name": "0-4",
    "id": "0-4",
    "alarmStatus": "Indeterminate",
    "installedEquipmentObjectType": "A900-IMA8S",
    "installedVersion": "",
    "supportedTps": [
      "GigabitEthernet-0-4-0",
      "GigabitEthernet-0-4-1",
      "GigabitEthernet-0-4-2",
      "GigabitEthernet-0-4-3",
      "GigabitEthernet-0-4-4",
      "GigabitEthernet-0-4-5",
      "GigabitEthernet-0-4-6",
      "GigabitEthernet-0-4-7"
    ],
    "alarmReportingIndicator": false,
    "serviceState": "IN_SERVICE",
    "owner": "",
    "installedSerialNumber": "FOC16338924",
    "installedPartNumber": "A900-IMA8S",
    "expectedEquipmentObjectType": "A900-IMA8S",
    "containedEquipmentHolders": [],
    "nativeEMSName": ""
  }
]
