=== ekarjun/Arjun_RA/arjun_ra/model/schema/models/TerminationPoint.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "title": "TerminationPoint",
    "properties": {
        "userLabel": { "type": "string" },
        "direction": { "enum": ["D_NA", "D_SOURCE", "D_BIDIRECTIONAL", "D_SINK"] },
        "name": { "type": "string" },
        "id": { "type": "string" },
        "alarmStatus": { "$ref": "AlarmStatus.json" },
        "containedCTPs": { "type": "array", "items": [{"$ref": "Ref.json"}] },
        "transmissionParams": { "type": "array", "items": [{"$ref": "LayeredParameters.json"}] },
        "serviceState": { "enum": ["OUT_OF_SERVICE_BY_MAINTENANCE", "SERV_NA", "OUT_OF_SERVICE", 
            "IN_SERVICE"] },
        "oids": { "type": "array", "items": [{"$ref": "OidEntry.json"}] },
        "connectionState": { "enum": ["NA", "SOURCE_CONNECTED", "SINK_CONNECTED", "BI_CONNECTED",
            "NOT_CONNECTED", "SOURCE_RESERVED", "SINK_RESERVED", "BI_RESERVED"] },
        "adminState": { "enum": ["AdminLockedMat", "AdminUnlocked", "AdminAutoInService", "AdminLockedDis"] },
        "owner": { "type": "string" },
        "nativeEmsName": { "type": "string" },
        "type": { "enum": ["TPT_PTP", "TPT_CTP", "TPT_TPPool", "TPT_FTP"] },
        "tpMappingMode": { "enum": ["TM_TERMINATED_AND_AVAILABLE_FOR_MAPPING", "TM_NA", 
            "TM_NEITHER_TERMINATED_NOR_AVAILABLE_FOR_MAPPING"] }
    },
    "additionalProperties": false,
    "required": [
        "userLabel", "direction", "name", "id", "alarmStatus", 
        "containedCTPs", "transmissionParams", "serviceState", "oids", "connectionState", 
        "adminState", "owner", "nativeEmsName", "type", "tpMappingMode"]
}

=== ekarjun/Arjun_RA/arjun_ra/model/data/example-termpoints.json
[
  {
    "userLabel": "GigabitEthernet 0/2/0",
    "direction": "D_NA",
    "name": "GigabitEthernet-0-2-0",
    "alarmStatus": "Indeterminate",
    "containedCTPs": [],
    "transmissionParams": [
      {
        "layer": "LR_PHYSICAL_OPTICAL",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_OPTICAL_SECTION",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_Optical_Channel",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_DSR_10Gigabit_Ethernet",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "INACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_DSR_Gigabit_Ethernet",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_Ethernet",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_CLIENT_ERP",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      }
    ],
    "serviceState": "OUT_OF_SERVICE",
    "oids": [],
    "connectionState": "NA",
    "adminState": "AdminAutoInService",
    "owner": "",
    "nativeEmsName": "",
    "type": "TPT_PTP",
    "id": "GigabitEthernet-0-2-0",
    "tpMappingMode": "TM_NA"
  },
  {
    "userLabel": "GigabitEthernet 0/2/1",
    "direction": "D_NA",
    "name": "GigabitEthernet-0-2-1",
    "alarmStatus": "Indeterminate",
    "containedCTPs": [],
    "transmissionParams": [
      {
        "layer": "LR_PHYSICAL_OPTICAL",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_OPTICAL_SECTION",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_Optical_Channel",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_DSR_10Gigabit_Ethernet",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "INACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_DSR_Gigabit_Ethernet",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_Ethernet",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_CLIENT_ERP",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      }
    ],
    "serviceState": "OUT_OF_SERVICE",
    "oids": [],
    "connectionState": "NA",
    "adminState": "AdminAutoInService",
    "owner": "",
    "nativeEmsName": "",
    "type": "TPT_PTP",
    "id": "GigabitEthernet-0-2-1",
    "tpMappingMode": "TM_NA"
  },
  {
    "userLabel": "GigabitEthernet 0/2/2",
    "direction": "D_NA",
    "name": "GigabitEthernet-0-2-2",
    "alarmStatus": "Indeterminate",
    "containedCTPs": [],
    "transmissionParams": [
      {
        "layer": "LR_PHYSICAL_OPTICAL",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_OPTICAL_SECTION",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_Optical_Channel",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_DSR_10Gigabit_Ethernet",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "INACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_DSR_Gigabit_Ethernet",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_Ethernet",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_CLIENT_ERP",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      }
    ],
    "serviceState": "OUT_OF_SERVICE",
    "oids": [],
    "connectionState": "NA",
    "adminState": "AdminAutoInService",
    "owner": "",
    "nativeEmsName": "",
    "type": "TPT_PTP",
    "id": "GigabitEthernet-0-2-2",
    "tpMappingMode": "TM_NA"
  },
  {
    "userLabel": "GigabitEthernet 0/2/3",
    "direction": "D_NA",
    "name": "GigabitEthernet-0-2-3",
    "alarmStatus": "Indeterminate",
    "containedCTPs": [],
    "transmissionParams": [
      {
        "layer": "LR_PHYSICAL_OPTICAL",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_OPTICAL_SECTION",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_Optical_Channel",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_DSR_10Gigabit_Ethernet",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "INACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_DSR_Gigabit_Ethernet",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_Ethernet",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      },
      {
        "layer": "LR_CLIENT_ERP",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
        "serviceState": "IN_SERVICE",
        "location": "",
        "alarmReporting": "on"
      }
    ],
    "serviceState": "OUT_OF_SERVICE",
    "oids": [],
    "connectionState": "NA",
    "adminState": "AdminAutoInService",
    "owner": "",
    "nativeEmsName": "",
    "type": "TPT_PTP",
    "id": "GigabitEthernet-0-2-3",
    "tpMappingMode": "TM_NA"
  },
  {
    "userLabel": "GigabitEthernet 0/2/4",
    "direction": "D_NA",
    "name": "GigabitEthernet-0-2-4",
    "alarmStatus": "Indeterminate",
    "containedCTPs": [],
    "transmissionParams": [
      {
        "layer": "LR_PHYSICAL_OPTICAL",
        "layerInUse": true,
        "potentialFutureSetupIndicator": "RSU_POINT_TO_POINT",
        "thisLayerActive": "ACTIVE",
